#!/bin/bash

NumC=10
PERC=80
FR=15
PROG=./
MOVPATH=./

if [ ! -d "$PROG" ] || [ ! -d "$MOVPATH" ]
then
   echo "dir path/s do not exist!"
   exit 1
fi

echo "program ran at $(date '+%Y-%m-%d %H:%M:%S')" 

cd $PROG

arg=12
DT_ST=$(date +%Y%m%d%H%M%S -d "$arg hours ago")
DT_EN=$(date +%Y%m%d%H%M%S)

FD=$(date +%a-%H)

python ./train-km.py 1 $NumC $DT_ST $DT_EN
python ./predict-km.py $PERC

./moviefrm-list-ni $FR

mv $MOVPATH/ffnames.mp4 $MOVPATH/ffnames-$FD.mp4
echo "$MOVPATH/ffnames-$FD.mp4 saved"
